<div class="section">
            <a id="main-content"></a>
                    <h1 id="page-title" class="title">
          User account        </h1>
                          <div class="tabs">
          <h2 class="element-invisible">Primary tabs</h2><ul class="tabs primary"><li><a href="/acquia_drupal/user/register">Create new account</a></li>
<li class="active"><a class="active" href="/acquia_drupal/user">Log in<span class="element-invisible">(active tab)</span></a></li>
<li><a href="/acquia_drupal/user/password">Request new password</a></li>
</ul>        </div>
                          <div class="region region-content">
    <div class="block block-system" id="block-system-main">


  <div class="content">
    <form accept-charset="UTF-8" id="user-login" method="post" action="/acquia_drupal/user"><div><div class="form-item form-type-textfield form-item-name">
  <label for="edit-name">Username <span title="This field is required." class="form-required">*</span></label>
 <input type="text" class="form-text required" maxlength="60" size="60" value="" name="name" id="edit-name">
<div class="description">Enter your 192.168.2.64 username.</div>
</div>
<div class="form-item form-type-password form-item-pass">
  <label for="edit-pass">Password <span title="This field is required." class="form-required">*</span></label>
 <input type="password" class="form-text required" maxlength="128" size="60" name="pass" id="edit-pass">
<div class="description">Enter the password that accompanies your username.</div>
</div>
<input type="hidden" value="form-pd5P1c7F2ugRqxz8HhwFLtoCKdtDSnDx2Dcnv-ysDns" name="form_build_id">
<input type="hidden" value="user_login" name="form_id">
<div id="edit-actions" class="form-actions form-wrapper"><input type="submit" class="form-submit" value="Log in" name="op" id="edit-submit"></div></div></form>  </div>
</div>
  </div>

    </div>